{{- if not .Values.enteCredentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.yaml: {{ include "ente.credentials.data" . | b64enc }}
{{- end -}}
