{{- if not .Values.enteCredentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.yaml: |-
    {{- include "ente.credentials.data" . | nindent 4 }}
{{- end -}}
