{{- if .Values.ingress.web.enabled -}}
{{- $hostnameMap := dict "public-albums" "albums" "photos" "photos" "accounts" "accounts" "auth" "auth" "cast" "cast" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ente.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ingress
  {{- with .Values.ingress.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.web.className }}
  ingressClassName: {{ .Values.ingress.web.className }}
  {{- end }}
  rules:
    {{- range .Values.web.service.ports -}}
    {{- $helperName := index $hostnameMap .name -}}
    {{- $hostname := tpl (printf "{{ include \"ente.hostname.%s\" . }}" $helperName) $ }}
    - host: {{ $hostname | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.web.path }}
            pathType: {{ $.Values.ingress.web.pathType }}
            backend:
              service:
                name: {{ include "ente.fullname" $ }}-web
                port:
                  name: {{ .name }}
    {{- end }}
  {{- if .Values.ingress.web.tls }}
  tls:
    {{- range .Values.ingress.web.tls }}
    - hosts:
      {{- if .hosts }}
        {{- toYaml .hosts | nindent 8 }}
      {{- else }}
        {{- range $.Values.web.service.ports }}
        {{- $helperName := index $hostnameMap .name }}
        - {{ tpl (printf "{{ include \"ente.hostname.%s\" . }}" $helperName) $ | quote }}
        {{- end }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
