{{- if (and .Values.minioSetup.enabled (.Values.minioSetup.buckets) ) }}
{{- $minioUrl := default (printf "http://%s-minio:9000" .Release.Name) .Values.minioSetup.minioUrl }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ente.fullname" . }}-minio-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio-setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "ente.fullname" . }}-minio-setup
      labels:
        {{- include "ente.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: "minio/mc:latest"
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio {{ $minioUrl }} $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
              {{- range .Values.minio.buckets }}
              mc mb myminio/{{ .name }} --ignore-existing;
              {{- end }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.auth.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio
                  key: root-password
{{- end }}
