apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ente.fullname" . }}-museum-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
    app.kubernetes.io/component: museum-config
data:
  museum.yaml: |-
    {{- include "ente.museum.config.data" . | nindent 4 }}
