apiVersion: v1
kind: Service
metadata:
  name: {{ include "ente.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
  {{- range .Values.web.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "ente.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ente.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "ente.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      {{- with (.Values.web.podAnnotations | default .Values.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ente.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ente.serviceAccount.name" . }}
      securityContext:
        {{- .Values.web.podSecurityContext | default .Values.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: web
          securityContext:
            {{- .Values.web.securityContext | default .Values.securityContext | toYaml | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.web.config.nodeEnv | quote }}
            - name: ENTE_API_ORIGIN
              value: {{ include "ente.web.apiOrigin" . | quote }}
            - name: ENTE_ALBUMS_ORIGIN
              value: {{ include "ente.apps.publicAlbumsUrl" . | quote }}
            # These are not really required, but documented here just in case:
            # they are used in js files when running yarn to get the above values.
            # The dockerfile uses a placeholder at buildtime that gets replaced at
            # runtime: https://github.com/ente-io/ente/blob/e173982115c6aa6c2c09ecde1e0dccb8aa3dbf30/web/Dockerfile#L61-L66
            # - name: NEXT_PUBLIC_ENTE_ENDPOINT
            #   value: {{ include "ente.web.apiOrigin" . | quote }}
            # - name: NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT
            #   value: {{ include "ente.apps.publicAlbumsUrl" . | quote }}
          ports:
          {{- range .Values.web.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ (first .Values.web.service.ports).targetPort | default 3000 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ (first .Values.web.service.ports).targetPort | default 3000 }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
