envFromConfigMap:
  data:
    # mysql --host="$LEAN_DB_HOST" --user="$LEAN_DB_USER" --database="$LEAN_DB_DATABASE" --password="$LEAN_DB_PASSWORD" --port="$LEAN_DB_PORT" --ssl-ca="$LEAN_DB_MYSQL_ATTR_SSL_CA"
    LEAN_DB_HOST: "maxscale-casa.mariadb.svc.cluster.local"
    # Path to the CA certificate where we mount it
    LEAN_DB_MYSQL_ATTR_SSL_CA: "/var/www/html/storage/mariadb-bundle/ca.crt"
    # Make sure to require server TLS verification
    LEAN_DB_MYSQL_ATTR_SSL_VERIFY_SERVER: "true"
    LEAN_DEFAULT_TIMEZONE: "Europe/Helsinki"

    LEAN_USE_S3: "true"
    LEAN_S3_BUCKET: "leantime"
    LEAN_S3_USE_PATH_STYLE_ENDPOINT: "true"
    LEAN_S3_REGION: "us-east-1"
    LEAN_S3_END_POINT: "https://minio.example.com"

    LEAN_EMAIL_RETURN: "no-reply@example.com"
    LEAN_EMAIL_USE_SMTP: "true"
    LEAN_EMAIL_SMTP_HOSTS: "smtp.gmail.com"

    LEAN_USE_REDIS: "true"
    LEAN_REDIS_HOST: "leantime.dragonfly.svc.cluster.local"
    LEAN_REDIS_PORT: "6379"
    LEAN_REDIS_SCHEME: "tcp"
    LEAN_REDIS_USERNAME: "leantime"

envFromSecret:
  # Enabled by default, this will require a secret "leantime-from-vault" with all variables
  # not in the ConfigMap and normally included in this data object
  existingSecret: leantime-env-from-vault

# For the mariadb bundle
volumes:
  - name: mariadb-bundle
    configMap:
      name: mariadb-bundle
      optional: false

volumeMounts:
  - name: mariadb-bundle
    # mariadb-bundle has a key ca.crt with the certificate bundle
    mountPath: "/var/www/html/storage/mariadb-bundle"
    readOnly: true

ingress:
  enabled: true
  className: "contour"
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    projectcontour.io/tls-cert-namespace: projectcontour
  hosts:
    - host: &hostName leantime.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - *hostName
      secretName: casa-wildcard

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Make sure the included mariadb chart is not enabled if using external!
mariadb:
  enabled: false

# MariaDB Operator Resources + Dragonfly
extraResources:
- apiVersion: k8s.mariadb.com/v1alpha1
  kind: Database
  metadata:
    name: casa-mariadb-cluster-leantime
  spec:
    characterSet: utf8mb4
    cleanupPolicy: Delete
    collate: utf8mb4_general_ci
    mariaDbRef:
      name: casa-mariadb-cluster
      namespace: mariadb
      waitForIt: true
    name: leantime
    requeueInterval: 10h
    retryInterval: 30s

- apiVersion: k8s.mariadb.com/v1alpha1
  kind: User
  metadata:
    name: casa-mariadb-cluster-leantime
  spec:
    cleanupPolicy: Delete
    host: '%'
    mariaDbRef:
      name: casa-mariadb-cluster
      namespace: mariadb
      waitForIt: true
    maxUserConnections: 10
    name: leantime
    passwordSecretKeyRef:
      # We use the same secret
      key: LEAN_DB_PASSWORD
      name: leantime-env-from-vault
    require:
      ssl: true
    requeueInterval: 10h
    retryInterval: 30s

- apiVersion: k8s.mariadb.com/v1alpha1
  kind: Grant
  metadata:
    name: casa-mariadb-cluster-leantime
  spec:
    cleanupPolicy: Delete
    database: leantime
    grantOption: true
    host: '%'
    mariaDbRef:
      name: casa-mariadb-cluster
      namespace: mariadb
      waitForIt: true
    privileges:
    - ALL PRIVILEGES
    requeueInterval: 10h
    retryInterval: 30s
    table: '*'
    username: leantime

- apiVersion: external-secrets.io/v1
  kind: ExternalSecret
  metadata:
    name: leantime-env-from-vault
  spec:
    refreshInterval: 5m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend-casa
    dataFrom:
      - extract:
          key: casa/leantime/env
