apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leantime.fullname" . }}
  labels:
    {{- include "leantime.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "leantime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "leantime.checksum" . | quote }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "leantime.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "leantime.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.envFromConfigMap.enabled .Values.envFromSecret.enabled .Values.extraEnvFrom }}
          envFrom:
            {{- if .Values.envFromConfigMap.enabled }}
            - configMapRef:
                name: {{ .Values.envFromConfigMap.existingConfigMap | default (printf "%s" (tpl .Values.envFromConfigMap.cmName $)) }}
            {{- end }}
            {{- if .Values.envFromSecret.enabled }}
            - secretRef:
                name: {{ .Values.envFromSecret.existingSecret | default (printf "%s" (tpl .Values.envFromSecret.secretName $)) }}
            {{- end}}
            {{- with .Values.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end}}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ ternary "/healthCheck.php" "/" .Values.testing.enabled }}
              port: http
          {{- /* No readinessProbe, so traffic will be allowed during app install */ -}}
          {{- if not .Values.testing.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.volumeMounts .Values.persistence.enabled }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            {{- if .Values.persistence.volumeMounts.plugins.enabled }}
            - name: {{ include "leantime.fullname" . }}
              mountPath: {{ .Values.persistence.volumeMounts.plugins.mountPath }}
              subPath: {{ .Values.persistence.volumeMounts.plugins.subPath }}
            {{- end }}
            {{- if .Values.persistence.volumeMounts.userFiles.enabled }}
            - name: {{ include "leantime.fullname" . }}
              mountPath: {{ .Values.persistence.volumeMounts.userFiles.mountPath }}
              subPath: {{ .Values.persistence.volumeMounts.userFiles.subPath }}
            {{- end }}
            {{- if .Values.persistence.volumeMounts.publicUserFiles.enabled }}
            - name: {{ include "leantime.fullname" . }}
              mountPath: {{ .Values.persistence.volumeMounts.publicUserFiles.mountPath }}
              subPath: {{ .Values.persistence.volumeMounts.publicUserFiles.subPath }}
            {{- end }}
            {{- end }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.volumes .Values.persistence.enabled }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: {{ include "leantime.fullname" . }}
          {{- if eq .Values.persistence.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ ternary (.Values.persistence.existingClaim | quote) (printf "%s" (include "leantime.fullname" .)) .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
