# Ente museum config file example to use with vault for an external secret contents
# e.g. under casa/ente/museum-credentials in Vault, with each field the same of the
# secret key in Vault, which would then create a secret similar to this yaml
  credentials.yaml: |-
    key:
      encryption: "a0VOTHJEOENhVGw1cURWMDMzczZncmVnUHZ3dkx4R0E="
      hash: "eWdVRDlDcFFhVFVYUVA3b1ZtTWxGUEtLcDBFVDFueEhKTGowb1RQM2F0NFFscEhaMzV4ZUx1Y1Z3cGZOcjk2Qg=="
    jwt:
      secret: "NTNTaElPUEtjaEhFemNmQ2kxMk1abnpqMHI1cTRzM2g="
    s3:
      are_local_buckets: false
      use_path_style_urls: true
      # Using Hetzner in Finland
      b2-eu-cen:
        key: "changeme"
        secret: "changeme1234"
        endpoint: "hel1.your-objectstorage.com"
        region: "eu-central"
        bucket: "b2-eu-cen"
      # Using Minio with SSL at home
      wasabi-eu-central-2-v3:
        key: "changeme"
        secret: "changeme1234"
        endpoint: "ente-minio:3000"
        region: "eu-central-2"
        bucket: "wasabi-eu-central-2-v3"
        compliance: false
      # Using Scaleway In France
      scw-eu-fr-v3:
        key: "changeme"
        secret: "changeme1234"
        endpoint: "s3.nl-ams.scw.cloud"
        region: "eu-central-2"
        bucket: "scw-eu-fr-v3"
    smtp:
      email: no-reply@my.domain
      host: smtp.gmail.com
      password: change
      port: 587
      sender-name: "My Ente"
      username: myuser
