name: Docs Commit

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - "renovate*"
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
jobs:
  check-artifact:
    runs-on: ubuntu-24.04
    outputs:
      has_patch: ${{ steps.check.outputs.has_patch }}
      patch_artifact_id: ${{ steps.check.outputs.patch_artifact_id }}
    steps:
      - name: Check for "docs-patch" artifact
        id: check
        run: |
          response=$(curl -sSL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "${{ github.event.workflow_run.artifacts_url }}")

          # See if any artifact has the name "docs-patch"
          artifact_id=$(echo "$response" | jq '.artifacts | map(select(.name == "docs-patch"))[0] | .id')

          if [ -z "$artifact_id" ] || [ "$artifact_id" = "null" ]; then
            echo "Artifact 'docs-patch' not found"
            echo "has_patch=false" >> "$GITHUB_OUTPUT"
            echo "patch_artifact_id=null" >> "$GITHUB_OUTPUT"
          else
            echo "Artifact 'docs-patch' found"
            echo "has_patch=true" >> "$GITHUB_OUTPUT"
            echo "patch_artifact_id=${artifact_id}" >> "$GITHUB_OUTPUT"
          fi
  apply-patch:
    needs: check-artifact
    if: (github.event.workflow_run.conclusion == 'success') && (github.event.workflow_run.head_repository.full_name == 'ocraviotto/helm-charts') && (needs.check-artifact.outputs.has_patch == 'true')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          artifact-ids: ${{ needs.check-artifact.outputs.patch_artifact_id }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip and Apply patch
        run: |
          git apply changes.patch || echo "Nothing to apply"

      - name: Commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add ':(icase)README*'
            git commit -m "chore(docs): update READMEs"
            git push --force-with-lease origin HEAD:${{ github.event.workflow_run.head_branch }}
          else
            echo "No README changes to commit."
          fi
