# Adapted from https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/ci.yaml
name: CI
permissions: {}

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: Lint and Test Charts
    runs-on: ubuntu-24.04
    needs: docs-check
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.18.1

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --config .github/linters/ct.yaml)"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_list=\"${changed//$'\n'/ }\"" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .github/linters/ct.yaml --helm-extra-set-args "--set=testing.enabled=true"

  super-linter:
    name: Lint All
    runs-on: ubuntu-24.04
    needs: docs-check
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@ffde3b2b33b745cb612d787f669ef9442b1339a6 # v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: false
          # If you set any of the VALIDATE_[LANGUAGE] variables to true, super-linter defaults to leaving any unset variable to false (only validate those languages).
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          # VALIDATE_CHECKOV: true - always scans everything and all charts have too much errors
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ENV: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_PYTHON: true
          #VALIDATE_RENOVATE: false # does not support newest renovate config
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_XML: true

  docs-check:
    name: Check Charts Docs
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Ensure documentation is updated
        uses: docker://jnorwood/helm-docs:v1.14.2

      - name: Ensure charts list is up-to-date too
        run: |
          # We should have yq installed...
          ./bin/update-readme.sh

      - name: Check for changes
        id: check
        run: |
          if git diff; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fail on forks
        if: steps.check.outputs.no_changes == 'false' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo -e "\n####### Git changes detected! Run helm-docs locally and commit README updates.\n"
          exit 1

      - name: Fail if not from branches renovate/
        if: steps.check.outputs.no_changes == 'false' && ! startsWith(github.event.pull_request.head.ref, 'renovate/')
        run: |
          echo -e "\n####### Git changes detected! Run helm-docs locally and commit README updates.\n"
          exit 1

      - name: Upload patch for Renovate branches
        if: |
          steps.check.outputs.no_changes == 'false' &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          startsWith(github.event.pull_request.head.ref, 'renovate/')
        run: |
          git diff > changes.patch
        continue-on-error: true

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: |
          steps.check.outputs.no_changes == 'false' &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          startsWith(github.event.pull_request.head.ref, 'renovate/')
        with:
          name: docs-patch
          path: changes.patch
